### ISSUE TITLE
nodejs_npm 'Zerorpc' do Installation fails

### ISSUE THREAD

**Issue by sernapallyanurag** [sous-chefs/nodejs#118] opened 2016-02-25 07:09 UTC
Error executing action `install` on resource 'nodejs_npm[zerorpc]'
#     ============================================================================

```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
execute[install NPM package zerorpc] (/var/chef/cache/cookbooks/nodejs/providers/npm.rb line 6)       had an error: Mixlib::ShellOut::ShellCommandFailed: Expected
 process to exit with [0], but received '1'
 ---- Begin output of npm install  -global zerorpc@0.9.6 ----
STDOUT: > msgpack@1.0.2 install /usr/local/lib/node_modules/zerorpc/node_mod
```

   ules/msgpack
    > node-gyp rebuild

   make: Entering directory `/usr/local/lib/node_modules/zerorpc/node_modules/m
   sgpack/build'
      CC(target) Release/obj.target/libmsgpack/deps/msgpack/objectc.o
      CC(target) Release/obj.target/libmsgpack/deps/msgpack/unpack.o
      CC(target) Release/obj.target/libmsgpack/deps/msgpack/vrefbuffer.o
      CC(target) Release/obj.target/libmsgpack/deps/msgpack/zone.o
      CC(target) Release/obj.target/libmsgpack/deps/msgpack/version.o
      AR(target) Release/obj.target/deps/msgpack/msgpack.a
      COPY Release/msgpack.a
      CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
    make: Leaving directory`/usr/local/lib/node_modules/zerorpc/node_modules/ms
gpack/build'
    /usr/local/lib
    └── (empty)
    STDERR: ../src/msgpack.cc: In function `void v8_to_msgpack(v8::Handle<v8::Va
lue>, msgpack_object*, msgpack_zone*, size_t)':
    ../src/msgpack.cc:126:93: error: could not convert`v8obj' from `v8::Handle<
v8::Value>' to`v8::Localv8::Value'
             mo->via.str.size = static_cast<uint32_t>(Nan::DecodeBytes(v8obj, Na
n::Encoding::UTF8));

```
             ^
../src/msgpack.cc:129:94: error: could not convert `v8obj' from `v8::Handle<
```

v8::Value>' to `v8::Localv8::Value'
             Nan::DecodeWrite((char*)mo->via.str.ptr, mo->via.str.size, v8obj, N
an::Encoding::UTF8);

```
              ^
../src/msgpack.cc:136:94: error: could not convert `result' from `v8::Handle
```

v8::Value' to `v8::Localv8::Value'
             mo->via.str.size = static_cast<uint32_t>(Nan::DecodeBytes(result, N
an::Encoding::UTF8));

```
              ^
../src/msgpack.cc:139:95: error: could not convert `result' from `v8::Handle
```

v8::Value' to `v8::Localv8::Value'
             Nan::DecodeWrite((char*)mo->via.str.ptr, mo->via.str.size, result,
Nan::Encoding::UTF8);

```
               ^
make: *** [Release/obj.target/msgpackBinding/src/msgpack.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/n
```

ode_modules/node-gyp/lib/build.js:276:23)
    gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:
797:12)
    gyp ERR! System Linux 3.19.0-49-generic
    gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-g
yp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /usr/local/lib/node_modules/zerorpc/node_modules/msgpack
    gyp ERR! node -v v0.10.26
    gyp ERR! node-gyp -v v3.2.1
    gyp ERR! not ok
    npm ERR! Linux 3.19.0-49-generic
    npm ERR! argv "node" "/usr/local/bin/npm" "install" "-global" "zerorpc@0.9.6
"
    npm ERR! node v0.10.26
    npm ERR! npm  v3.7.3
    npm ERR! code ELIFECYCLE

```
npm ERR! msgpack@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the msgpack@1.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

npm ERR! If you do, this is most likely a problem with the msgpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project wi
```

th:
    npm ERR!     npm bugs msgpack
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls msgpack
    npm ERR! There is likely additional logging output above.

```
npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
---- End output of npm install  -global zerorpc@0.9.6 ----
Ran npm install  -global zerorpc@0.9.6 returned 1

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/nodejs/recipes/npmpack.rb

 63: nodejs_npm "zerorpc" do
 64: version '0.9.6'
 65: action :install
 66: end
 67:

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/nodejs/recipes/npmpack.rb:63:in `fro
```

m_file'

```
nodejs_npm("zerorpc") do
  action [:install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :nodejs_npm
  cookbook_name "nodejs"
  recipe_name "npmpack"
  version "0.9.6"
  package "zerorpc"
end
```

Running handlers:
[2016-02-25T07:07:45+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-02-25T07:07:45+00:00] ERROR: Exception handlers complete
Chef Client failed. 30 resources updated in 03 minutes 12 seconds
[2016-02-25T07:07:45+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-sta
cktrace.out
[2016-02-25T07:07:45+00:00] FATAL: Please provide the contents of the stacktrace
.out file if you file a bug report
[2016-02-25T07:07:45+00:00] ERROR: nodejs_npm[zerorpc](nodejs::npmpack line 63)
 had an error: Mixlib::ShellOut::ShellCommandFailed: execute[install NPM package
 zerorpc](/var/chef/cache/cookbooks/nodejs/providers/npm.rb line 6) had an erro
r: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but
received '1'
---- Begin output of npm install  -global zerorpc@0.9.6 ----
STDOUT: > msgpack@1.0.2 install /usr/local/lib/node_modules/zerorpc/node_modules
/msgpack

> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/zerorpc/node_modules/msgpa
ck/build'
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/objectc.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/unpack.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/vrefbuffer.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/zone.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/version.o
  AR(target) Release/obj.target/deps/msgpack/msgpack.a
  COPY Release/msgpack.a
  CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
make: Leaving directory`/usr/local/lib/node_modules/zerorpc/node_modules/msgpac
k/build'
/usr/local/lib
└── (empty)
STDERR: ../src/msgpack.cc: In function `void v8_to_msgpack(v8::Handle<v8::Value>
, msgpack_object*, msgpack_zone*, size_t)':
../src/msgpack.cc:126:93: error: could not convert`v8obj' from `v8::Handle<v8::
Value>' to`v8::Localv8::Value'
         mo->via.str.size = static_cast<uint32_t>(Nan::DecodeBytes(v8obj, Nan::E
ncoding::UTF8));

```
         ^
```

../src/msgpack.cc:129:94: error: could not convert `v8obj' from`v8::Handle<v8::
Value>' to `v8::Localv8::Value'
         Nan::DecodeWrite((char*)mo->via.str.ptr, mo->via.str.size, v8obj, Nan::
Encoding::UTF8);

```
          ^
```

../src/msgpack.cc:136:94: error: could not convert `result' from`v8::Handle<v8:
:Value>' to `v8::Localv8::Value'
         mo->via.str.size = static_cast<uint32_t>(Nan::DecodeBytes(result, Nan::
Encoding::UTF8));

```
          ^
```

../src/msgpack.cc:139:95: error: could not convert `result' from`v8::Handle<v8:
:Value>' to `v8::Localv8::Value'
         Nan::DecodeWrite((char*)mo->via.str.ptr, mo->via.str.size, result, Nan:
:Encoding::UTF8);

```
           ^
```

make: **\* [Release/obj.target/msgpackBinding/src/msgpack.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_
modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:
12)
gyp ERR! System Linux 3.19.0-49-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/b
in/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/zerorpc/node_modules/msgpack
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm ERR! Linux 3.19.0-49-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-global" "zerorpc@0.9.6"
npm ERR! node v0.10.26
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! msgpack@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the msgpack@1.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the msgpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs msgpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls msgpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
---- End output of npm install  -global zerorpc@0.9.6 ----
Ran npm install  -global zerorpc@0.9.6 returned 1
[2016-02-25T07:07:45+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef ru
n process exited unsuccessfully (exit code 1)

**Comment by MarkGibbons** [comment] 2020-10-02 18:45
Triage effort:

- See if we can reproduce
- this looks like a package problem or npm problem. If so close this issue.

**Comment by MarkGibbons** [comment] 2020-10-03 19:35
Installing zerorpc using the command line and  "npm install zerorpc" fails.  It's not an issue with the cookbook.

**Closed by MarkGibbons** 2020-10-03 19:35 UTC
Labels: Needs Triage
