### ISSUE TITLE
nodejs cookbook does not install npm on ubuntu

### ISSUE THREAD

**Issue by jarrettj** [sous-chefs/nodejs#172] opened 2017-05-16 07:34 UTC
### Cookbook version
[Version of the cookbook where you are encountering the issue]
3.0.0

### Chef-client version
[Version of chef-client in your environment]
Chef: 12.18.31

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
Ubuntu 16.04

### Scenario:
[What you are trying to achieve and you can't?]
Trying to install npm cli.

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
My cookbook contains:
```
include_recipe "nodejs"
include_recipe "nodejs::npm"

nodejs_npm "bower"
```

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
npm should install bower.

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
The npm cli is not installed. So the lwrp nodejs_npm does not work.

Error output:
```
Error executing action `run` on resource 'execute[install NPM package bower]'
Errno::ENOENT
No such file or directory - npm
```

**Comment by eric-tucker** [comment] 2017-06-07 15:07
I can attest this is happening for me too.

**Comment by sljuka** [comment] 2017-06-11 22:06
This is also happening on my server. Ubuntu 16.04 even with both nodejs::default and nodejs::npm included. 
I remember having problems installing node on ubuntu when instaling it manually via apt-get. Node package is conflicting with an existing package on Ubuntu, so it gets screwed up. This issue might be related with this name conflict.
This post helped me resolve it manually:
https://stackoverflow.com/questions/34243719/how-to-install-npm-after-purge/34244847#34244847
I'm not yet sure if this can be fixed by configuring the recipe.

**Comment by sandyfox** [comment] 2017-07-14 00:26
+1

**Comment by jamescorkran** [comment] 2017-08-23 11:23
+1

**Comment by espoelstra** [comment] 2018-05-09 22:11
Those having this issue, are you setting `default['nodejs']['version'] = '6'` or something similar in your `attributes/default.rb` of your wrapper cookbook?

**Comment by stephanvierkant** [comment] 2019-07-11 14:32
Same problem here, Ubuntu 18.10. Just with default config, not a single option changes. It installes nodejs, but doesn't install npm.

**Comment by kategray** [comment] 2019-09-29 16:22
Can confirm that this issue persists with Chef 12 on Ubuntu 18.10. (Opsworks)

**Comment by MarkGibbons** [comment] 2020-10-02 18:23
Checking to see if this is still an issue.
Make sure the tests verify installation of nodejs and npm.

**Comment by MarkGibbons** [comment] 2020-10-03 19:42
I can't reproduce this error.  Given the age of the report and the old chef-client version I'm going to close the issue.

**Closed by MarkGibbons** 2020-10-03 19:42 UTC
Labels: Bug, Priority: Medium, hacktoberfest
